### ISSUE TITLE
Also See: maximist

### ISSUE THREAD

**Issue by timoxley** [asbjornenge/minimist-reverse#1]
Just FYI https://www.npmjs.com/package/maximist

**Comment by asbjornenge** [comment]
@timoxley hah! there is also https://www.npmjs.com/package/tsiminim :stuck_out_tongue: I wrote a PR for that one that never got merged, so I made a separate module. But I'll have a look at maximist :+1: Oh, and https://github.com/sindresorhus/dargs too apparently. :see_no_evil: 

One thing I wanted was that any '_' args go first in the output. But come to think of it that might be totally wrong for some commands...

**Comment by asbjornenge** [comment]
I'll note in the README the way this module structures the arguments and add links to those other two :+1: Hope that's cool :v:

**Comment by timoxley** [comment]
@asbjornenge You _could_ combine powers with @hughsk. Turns out both packages suck, for different reasons: :+1: 

``` js
maximist({
    hello: 'world'
  , spin: false
}).join(' ')

// '--hello world --no-spin'
minimistReverse({
    hello: 'world'
  , spin: false
})
// '--hello=world'

maximist({
    _: ['cmd'],
    a: 1,
    b: 'b',
    c: true,
    d: true,
    e: false,
    h: [1,2,3],
    bar: 'baz'
})
// Error: maximist currently only supports strings and booleans

minimistReverse({
    _: ['cmd'],
    a: 1,
    b: 'b',
    c: true,
    d: true,
    e: false,
    h: [1,2,3],
    bar: 'baz'
})
// 'cmd -acd -b=b -h=1 -h=2 -h=3 --bar=baz'

maximist({
    a: 1,
    b: 'b',
    c: true,
    d: true,
    e: false,
    bar: 'baz'
}).join(' ')
// '--a 1 --b b --c --d --no-e --bar baz'

minimistReverse({
    a: 1,
    b: 'b',
    c: true,
    d: true,
    e: false,
    bar: 'baz'
})
// '-acd -b=b --bar=baz'

maximist({
      hello: 'world'
    , falsey: false
    , truthy: true
    , numeric: 2
    , stringy: 'string'
  }).join(' ')
// '--hello world --no-falsey --truthy --numeric 2 --stringy string'

minimistReverse({
      hello: 'world'
    , falsey: false
    , truthy: true
    , numeric: 2
    , stringy: 'string'
  })
// '--truthy --hello=world --numeric=2 --stringy=string'
```

**Comment by timoxley** [comment]
and by "suck" I mean "has potential for improvement, yay" not "is shit and you should feel bad" :green_heart:

**Comment by asbjornenge** [comment]
@timoxley hah, no worries :smile: I like the --no-key handling for false. I could add that and make the = optional. Whaddaya think @hughsk?

But that seems to just bring us to the [dargs](https://github.com/sindresorhus/dargs) module, no? :stuck_out_tongue_closed_eyes:

**Comment by asbjornenge** [comment]
After looking into this a bit more I think the **dargs** module is clearly the best choice to gather around. What is the appropriate way to do that? unpublish?

The other option I see is for me to just direct people to dargs in the README. At least for me it was (apparently) not easy to discover... I searched npm for "minimist reverse" and although I see dargs now, I didn't think to click on it.

//cc @sindresorhus

**Comment by asbjornenge** [comment]
Went with updating the README since ppl had already installed the module.

**Comment by timoxley** [comment]
:+1:

**Comment by sindresorhus** [comment]
:+1: I tweaked the `dargs` description and added some more keywords. Hopefully that will make it easier to find it :)
